### ISSUE TITLE
Alternative formula response

### ISSUE THREAD

**Issue by zeileis** [Hapfelmeier/coat#13]
After my Psychoco presentation Jan de Neve suggested that it is possibly confusing to use a response specification with a `+` like

```
m1 + m2 ~ x1 + x2 + x3
```

He would have found it more intuitive to use

```
m1 - m2 ~ x1 + x2 + x3
```

because this reflects what is computed as the main response.

I liked this suggestion and we can easily support it by just internally replacing the `-` (if any) by a `+`:

```
 if(formula[[2L]][[1L]] == as.name("-")) formula[[2L]][[1L]] <- as.name("+")
```

Do you agree?

**Comment by Hapfelmeier** [comment]
I do! May I ask you for a respective pull request?

**Comment by Hapfelmeier** [comment]
Many Thanks! This is a very much appreciated contribution!
