### ISSUE TITLE
Formula interface

### ISSUE THREAD

**Issue by zeileis** [Hapfelmeier/coat#4]
I think it would be nice if `coat()` had a formula interface like other `partykit` trees as well. Possibly, this might be used to support both long and wide format of the data. Also, as a side effect, this could be leveraged to provide a `predict()` method.

**Comment by Hapfelmeier** [comment]
I also wanted to have a formula interface, but I was pressed for time when I implemented it, so I chose the way that was easier for me.

**Comment by zeileis** [comment]
Fair enough. The semester starts on Monday.. but if I find the time I might suggest a PR.

**Comment by Hapfelmeier** [comment]
Very much appreciated!

**Comment by zeileis** [comment]
Just fyi: I had a stab at this now, see https://github.com/Hapfelmeier/coat/compare/main...zeileis:coat:formula-interface

The core idea is that the response is bivariate a la `y1 + y2 ~ x` and differences or means of `y1` and `y2` can always be computed subsequently (when needed).

I hope that I have already adapted all methods and auxiliary functions as needed but I need to run a few more tests and then adapt the documentation.

**Comment by zeileis** [comment]
I finally found some time to wrap this up. Sorry for changing so many things...I'm happy to discuss these via video conference if you find it hard to track the many changes I made.

**Comment by zeileis** [comment]
Closing this issue now, it has been ddressed by PR https://github.com/Hapfelmeier/coat/pull/8.
