### ISSUE TITLE
coat object representation

### ISSUE THREAD

**Issue by zeileis** [Hapfelmeier/coat#5]
Currently, `coat()` returns different objects for `ctree`-based models and `mob`-based models. It would be nice to avoid this or at least reduce the differences. This could be done by settling either for a `constparty` or `modelparty` view of `coat` and adding some infos for the other model class.

In any case, it would be good to unify printing and deciding on which quantity to report (bias+variance vs. bias+standard-deviation vs. limits of agreement)

**Comment by Hapfelmeier** [comment]
I quickly tried something for ctree, but it doesn't work for mob for obvious reasons:

#' @describeIn coat function to print the result of \code{coat}.
#' @export
print.coat <- function(x, digits = 2, ...) {
  if (inherits(mytree3, "modelparty")) {
    x <- partykit::as.constparty(x)
  }
  
  terminalnodeids. <- partykit::nodeids(x, terminal = TRUE)
  out <- t(predict(x, id = terminalnodeids., FUN = function(y, w) c(mean(y), sd(y))))
  rownames(out) <- c("Bias", "SD")
  colnames(out) <- paste("Node", terminalnodeids.)
  
  print(out, na.print="", ...)
}

**Comment by Hapfelmeier** [comment]
I now added a print() function, which is actually a print.constparty() function, for coat objects.
