### ISSUE TITLE
Horizontal line at the bottom of ggparty plot?

### ISSUE THREAD

**Issue by zeileis** [Hapfelmeier/coat#6]
Is the horizontal line at the bottom of the ggparty plot intended?

**Comment by Hapfelmeier** [comment]
No, that is not intended. But I would like to work with your new node_baplot implementation anyway.

**Comment by zeileis** [comment]
Great! Then I would suggest to move the current `plot()` method to an `autoplot()` method. Then we still have it available when `ggplot2` support would be handy.

**Comment by Hapfelmeier** [comment]
I was finally able to remove the line.
